# fly.toml app configuration file generated for hoyofeed on 2024-01-25T17:36:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hoyofeed'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  FEED_LANG = "ja-jp"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
